FROM debian:buster-slim

RUN apt update -y && \
    apt install -y git wget bash libssl-dev build-essential libc6 && \
    wget http://www.jsoftware.com/download/j903/install/j903_linux64.tar.gz && \
    tar xvfz j903_linux64.tar.gz

